#!/usr/bin/env python3


import os
import sys
from src import new 
from src import add 
from src import scripts 
from src import util 
from src import Config


def main(args):
    if len(args) == 0:
        print("Invalid arguments")
        return
    if args[0] == "--help" or args[0] == "-h":
        help()
        return
    elif args[0] == "--version" or args[0] == "-v":
        version()
        return
    elif args[0] == "new":
        new(args[1:])
        return

    config = Config()
    config.parse_config()

    if scripts(args, config["scripts"]):
        return
    elif args[0] == "add":
        add(args[1:], config)
    else:
        print("Invalid arguments")


if __name__ == "__main__":
    main(sys.argv[1:])
