#!/usr/bin/env python3


import os
import sys
from src import new 
from src import add 
from src import Config
from src import scripts 
from src import build
from src import util 


def main(args):
    if len(args) == 0:
        sys.exit("Invalid arguments")
    if args[0] == "help" or args[0] == "--help" or args[0] == "-h":
        with open("man/help.txt", "r") as f:
            print(f.read())
            print("CMaker version 1.2.1")
        return
    elif args[0] == "--version" or args[0] == "-v":
        print("CMaker version 1.2.1")
        return
    elif args[0] == "new":
        new(args[1:])
        return

    config = Config()
    config.parse_config()

    if scripts(args, config["scripts"]):
        return
    elif args[0] == "add":
        add(args[1:], config)
    elif args[0] == "build":
        build(args[1:], config)
    else:
        print("Invalid arguments")


if __name__ == "__main__":
    main(sys.argv[1:])
