#!/usr/bin/env python3
import os, sys
from src import help, version, new, build, run, clean, add, scripts, util

def main(args):
    if len(args) == 0:
        print("Invalid arguments")
        return
    if scripts(args):
        return
    if args[0] == "--help" or args[0] == "-h":
        help()
    elif args[0] == "--version" or args[0] == "-v":
        version()
    elif args[0] == "new":
        __unbox()
        new(args[1:])
    elif args[0] == "build":
        build(args[1:])
    elif args[0] == "run":
        run(args[1:])
    elif args[0] == "clean":
        clean(args[1:])
    elif args[0] == "add":
        add(args[1:])
    else:
        print("Invalid arguments")

def __unbox():
    home_dir = os.path.expanduser("~")
    check_path = os.path.join(home_dir, ".scripts/cmaker/templates/.cmaker/unbox.txt")
    if os.path.exists(check_path):
        fix_path = os.path.join(home_dir, ".scripts/cmaker/templates/default")
        bin_path = os.path.join(fix_path, "bin")
        if not os.path.exists(bin_path):
            util.mkdir(fix_path, "bin")
        build_path = os.path.join(fix_path, "build")
        if not os.path.exists(bin_path):
            util.mkdir(fix_path, "build")
        os.system("rm -rdf {}".format(check_path))

if __name__ == "__main__":
    main(sys.argv[1:])
